// ==========================================
// TIPOS PARA SISTEMA DE COTIZACIONES
// ==========================================

// Tipos de precio para servicios/productos
export type PriceType = 'fixed' | 'hourly' | 'range' | 'multiplier';

// Item del catálogo de servicios
export interface CatalogItem {
  id: string;
  userId: number;
  name: string;
  description: string;
  priceType: PriceType;
  price: number;           // Precio base o fijo
  priceMax?: number;       // Para rangos (precio máximo)
  unit?: string;           // "hora", "usuario", "licencia", etc.
  photo?: string;          // URL de imagen/icono
  icon?: string;           // Emoji o icono
  category?: string;       // Categoría del servicio
  isActive: boolean;
  order: number;
  createdAt: Date;
  updatedAt: Date;
}

// Cliente de cotización
export interface QuoteClient {
  name: string;
  email?: string;
  phone?: string;
  whatsapp?: string;
  company?: string;
}

// Item dentro de una cotización
export interface QuoteItem {
  catalogItemId?: string;  // Referencia al catálogo (opcional si es custom)
  name: string;
  description?: string;
  priceType: PriceType;
  unitPrice: number;
  quantity: number;
  total: number;
  isOptional?: boolean;    // Para upselling en la propuesta
  isSelected?: boolean;    // Si el cliente lo seleccionó
}

// Estados de la cotización
export type QuoteStatus = 
  | 'draft'       // 🌑 Borrador
  | 'sent'        // 🟡 Enviada
  | 'viewed'      // 👁️ Vista
  | 'approved'    // 🟢 Aprobada
  | 'rejected'    // 🔴 Rechazada
  | 'expired';    // ⚫ Expirada

// Cotización completa
export interface Quote {
  id: string;
  shortCode: string;       // Código corto para URL (ej: q8s7d6)
  userId: number;          // Proveedor/profesional
  client: QuoteClient;
  items: QuoteItem[];
  optionalItems?: QuoteItem[];  // Items opcionales para upselling
  
  // Totales
  subtotal: number;
  discount?: number;
  discountType?: 'percentage' | 'fixed';
  tax?: number;
  total: number;
  
  // Configuración
  currency: string;        // MXN, USD, etc.
  validDays: number;       // Días de vigencia
  expiresAt: Date;
  notes?: string;          // Notas/condiciones
  requiresDeposit?: boolean;
  depositPercent?: number;
  
  // Estado y tracking
  status: QuoteStatus;
  viewCount: number;
  lastViewedAt?: Date;
  
  // Firma digital
  signatureImage?: string; // URL de la firma PNG
  signedAt?: Date;
  signedByName?: string;
  signedByIp?: string;
  
  // Pago (si aplica)
  paymentIntentId?: string;
  paidAt?: Date;
  paidAmount?: number;
  
  // Metadatos
  createdAt: Date;
  updatedAt: Date;
  sentAt?: Date;
  
  // Auto-cotizador
  isAutoGenerated?: boolean;  // Si fue generado por el widget público
  leadSource?: string;        // Origen del lead
}

// Configuración del auto-cotizador para la página web
export interface QuoteWidgetConfig {
  userId: number;
  isEnabled: boolean;
  title: string;
  subtitle?: string;
  buttonText: string;
  
  // Categorías seleccionables
  categories: {
    id: string;
    name: string;
    items: string[];  // IDs de catalog items
  }[];
  
  // Estilo
  primaryColor: string;
  showPrices: boolean;       // Mostrar precios antes del lead capture
  requireContactForPrices: boolean;
  
  // Lead capture
  requireName: boolean;
  requireEmail: boolean;
  requirePhone: boolean;
  
  // Mensajes
  successMessage: string;
  
  createdAt: Date;
  updatedAt: Date;
}

// Respuesta/comentario en cotización
export interface QuoteComment {
  id: string;
  quoteId: string;
  authorType: 'provider' | 'client';
  authorName: string;
  message: string;
  createdAt: Date;
}

// Notificación de cotización
export interface QuoteNotification {
  id: string;
  userId: number;
  quoteId: string;
  type: 'new_quote_request' | 'quote_viewed' | 'quote_approved' | 'quote_rejected' | 'quote_expired';
  title: string;
  message: string;
  isRead: boolean;
  createdAt: Date;
}

// Stats del dashboard
export interface QuoteStats {
  totalQuotes: number;
  draftCount: number;
  sentCount: number;
  viewedCount: number;
  approvedCount: number;
  rejectedCount: number;
  expiredCount: number;
  
  // Métricas de dinero
  totalApprovedValue: number;
  avgQuoteValue: number;
  conversionRate: number;  // % de aprobadas vs enviadas
  
  // Este mes
  monthlyQuotes: number;
  monthlyApproved: number;
  monthlyValue: number;
}

// Para el Kanban/Pipeline
export interface QuotePipelineColumn {
  id: QuoteStatus;
  title: string;
  emoji: string;
  color: string;
  quotes: Quote[];
}
